name: Node.js CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Add Tezos PPA
        run: sudo add-apt-repository ppa:serokell/tezos -y && sudo apt-get update

      - name: Install Tezos Client
        run: sudo apt-get install tezos-client -y

      - run: npm ci
      - run: npm run build --if-present
      - run: npm run completium_init
      - run: npm run gen-binding
      - run: npm run mockup_init
      - run: npm test
